### ISSUE TITLE
mplfonts init 失败

### ISSUE THREAD

**Issue by Sciroccogti** [Clarmy/mplfonts#9]
```python
Traceback (most recent call last):
  File "/shared/conda/envs/bolt/bin/mplfonts", line 8, in <module>
    sys.exit(cli())
  File "/shared/conda/envs/bolt/lib/python3.10/site-packages/mplfonts/bin/cli.py", line 51, in cli
    fire.Fire(
  File "/shared/conda/envs/bolt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/shared/conda/envs/bolt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/shared/conda/envs/bolt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/shared/conda/envs/bolt/lib/python3.10/site-packages/mplfonts/bin/cli.py", line 17, in init
    install_fonts()
  File "/shared/conda/envs/bolt/lib/python3.10/site-packages/mplfonts/util/manage.py", line 108, in install_fonts
    font_names.append(get_font_name(mpl_font_fp))
  File "/shared/conda/envs/bolt/lib/python3.10/site-packages/mplfonts/util/manage.py", line 70, in get_font_name
    meta_instance = FontMeta(font_fp)
  File "/shared/conda/envs/bolt/lib/python3.10/site-packages/fontmeta.py", line 457, in __init__
    self.FONT = TTFont(fontfile)
  File "/shared/conda/envs/bolt/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 147, in __init__
    self.reader = SFNTReader(file, checkChecksums, fontNumber=fontNumber)
  File "/shared/conda/envs/bolt/lib/python3.10/site-packages/fontTools/ttLib/sfnt.py", line 82, in __init__
    raise TTLibError("Not a TrueType or OpenType font (bad sfntVersion)")
fontTools.ttLib.TTLibError: Not a TrueType or OpenType font (bad sfntVersion)
```

**Comment by Clarmy** [comment]
@Sciroccogti 什么操作系统？ mplfonts 的版本号是多少？

**Comment by Sciroccogti** [comment]
> @Sciroccogti 什么操作系统？ mplfonts 的版本号是多少？

Ubuntu 22.04, mplfonts 0.0.8
